import type { Agent } from "../types/agent";

// Placeholder data — kept for fallback/storybook; real data is fetched from /api/agents
export const MOCK_AGENTS: Agent[] = [
  {
    id: "agt_01",
    name: "Customer Support Agent",
    description: "Handles tier-1 customer queries, FAQs, and ticket creation.",
    model: "claude-3-5-sonnet",
    status: "active",
    temperature: 0.3,
    max_tokens: 2048,
    enabled_tool_ids: [],
    knowledge_collection_ids: [],
    tools_count: 3,
    kb_count: 2,
    conversations_count: 1248,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-06-20T14:30:00Z",
  },
  {
    id: "agt_02",
    name: "Sales Assistant",
    description: "Qualifies leads, answers product questions, schedules demos.",
    model: "gpt-4o",
    status: "active",
    temperature: 0.5,
    max_tokens: 4096,
    enabled_tool_ids: [],
    knowledge_collection_ids: [],
    tools_count: 2,
    kb_count: 1,
    conversations_count: 430,
    created_at: "2024-02-10T09:00:00Z",
    updated_at: "2024-06-18T11:00:00Z",
  },
  {
    id: "agt_03",
    name: "Technical Documentation Bot",
    description: "Answers developer questions from API docs and GitHub issues.",
    model: "claude-3-5-sonnet",
    status: "draft",
    temperature: 0.1,
    max_tokens: 8192,
    enabled_tool_ids: [],
    knowledge_collection_ids: [],
    tools_count: 0,
    kb_count: 3,
    conversations_count: 0,
    created_at: "2024-06-01T08:00:00Z",
    updated_at: "2024-06-01T08:00:00Z",
  },
];
