"""Initial schema

Revision ID: 2739e75eea89
Revises:
Create Date: 2026-07-04 05:35:50.255982

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2739e75eea89"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    op.create_table(
        "alert_events",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("rule_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_events_tenant_id"), "alert_events", ["tenant_id"], unique=False)
    op.create_table(
        "alert_rules",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("operator", sa.String(length=10), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("window_minutes", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_tenant_id"), "alert_rules", ["tenant_id"], unique=False)
    op.create_table(
        "cost_records",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_records_tenant_id"), "cost_records", ["tenant_id"], unique=False)
    op.create_table(
        "indexed_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=100), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexed_documents_document_id"), "indexed_documents", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_indexed_documents_tenant_id"), "indexed_documents", ["tenant_id"], unique=False
    )
    op.create_table(
        "mcp_servers",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("server_url", sa.String(length=1024), nullable=False),
        sa.Column("api_key", sa.String(length=512), nullable=True),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mcp_servers_tenant_id"), "mcp_servers", ["tenant_id"], unique=False)
    op.create_table(
        "offline_messages",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("session_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("visitor_id", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_type", sa.String(length=50), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("client_ts", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_offline_messages_session_id"), "offline_messages", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_offline_messages_tenant_id"), "offline_messages", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_offline_messages_visitor_id"), "offline_messages", ["visitor_id"], unique=False
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompts_name"), "prompts", ["name"], unique=False)
    op.create_index(op.f("ix_prompts_tenant_id"), "prompts", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_configs",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("llm_api_key", sa.String(length=512), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column("embeddings_model", sa.String(length=100), nullable=False),
        sa.Column("daily_request_limit", sa.Integer(), nullable=False),
        sa.Column("monthly_token_limit", sa.Integer(), nullable=False),
        sa.Column("branding", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenant_configs_tenant_id"), "tenant_configs", ["tenant_id"], unique=True
    )
    op.create_table(
        "tenants",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("plan", sa.String(length=50), server_default=sa.text("'free'"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("settings", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "tool_audit_log",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("conversation_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("arguments", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_audit_log_conversation_id"),
        "tool_audit_log",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_audit_log_tenant_id"), "tool_audit_log", ["tenant_id"], unique=False
    )
    op.create_table(
        "usage_records",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_records_tenant_id"), "usage_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "webhook_configs",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("secret", sa.String(length=512), nullable=True),
        sa.Column("events", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_configs_tenant_id"), "webhook_configs", ["tenant_id"], unique=False
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("config_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_config_id"), "webhook_deliveries", ["config_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_tenant_id"), "webhook_deliveries", ["tenant_id"], unique=False
    )
    op.create_table(
        "widget_sessions",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("visitor_id", sa.String(length=255), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("meta_data", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_widget_sessions_tenant_id"), "widget_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_widget_sessions_visitor_id"), "widget_sessions", ["visitor_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_api_keys",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(
        op.f("ix_tenant_api_keys_tenant_id"), "tenant_api_keys", ["tenant_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.Uuid(as_uuid=False),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("conversation_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("tenant_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)

    # --- RLS Policies ---
    op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation ON tenants FOR ALL USING (id = current_setting('app.tenant_id', TRUE)::UUID) WITH CHECK (id = current_setting('app.tenant_id', TRUE)::UUID);"
    )

    op.execute("ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE conversations FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY conversation_isolation ON conversations FOR ALL USING (tenant_id = current_setting('app.tenant_id', TRUE)::UUID) WITH CHECK (tenant_id = current_setting('app.tenant_id', TRUE)::UUID);"
    )

    op.execute("ALTER TABLE messages ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE messages FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY message_isolation ON messages FOR ALL USING (tenant_id = current_setting('app.tenant_id', TRUE)::UUID) WITH CHECK (tenant_id = current_setting('app.tenant_id', TRUE)::UUID);"
    )

    op.execute("ALTER TABLE mcp_servers ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE mcp_servers FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY mcp_server_isolation ON mcp_servers FOR ALL USING (tenant_id = current_setting('app.tenant_id', TRUE)::UUID) WITH CHECK (tenant_id = current_setting('app.tenant_id', TRUE)::UUID);"
    )

    op.execute("ALTER TABLE webhook_configs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE webhook_configs FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY webhook_config_isolation ON webhook_configs FOR ALL USING (tenant_id = current_setting('app.tenant_id', TRUE)::UUID) WITH CHECK (tenant_id = current_setting('app.tenant_id', TRUE)::UUID);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- RLS Policies Teardown ---
    op.execute("DROP POLICY IF EXISTS webhook_config_isolation ON webhook_configs;")
    op.execute("ALTER TABLE webhook_configs DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP POLICY IF EXISTS mcp_server_isolation ON mcp_servers;")
    op.execute("ALTER TABLE mcp_servers DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP POLICY IF EXISTS message_isolation ON messages;")
    op.execute("ALTER TABLE messages DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP POLICY IF EXISTS conversation_isolation ON conversations;")
    op.execute("ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP POLICY IF EXISTS tenant_isolation ON tenants;")
    op.execute("ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_tenant_api_keys_tenant_id"), table_name="tenant_api_keys")
    op.drop_table("tenant_api_keys")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_widget_sessions_visitor_id"), table_name="widget_sessions")
    op.drop_index(op.f("ix_widget_sessions_tenant_id"), table_name="widget_sessions")
    op.drop_table("widget_sessions")
    op.drop_index(op.f("ix_webhook_deliveries_tenant_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_config_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_webhook_configs_tenant_id"), table_name="webhook_configs")
    op.drop_table("webhook_configs")
    op.drop_index(op.f("ix_usage_records_tenant_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_tool_audit_log_tenant_id"), table_name="tool_audit_log")
    op.drop_index(op.f("ix_tool_audit_log_conversation_id"), table_name="tool_audit_log")
    op.drop_table("tool_audit_log")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_tenant_configs_tenant_id"), table_name="tenant_configs")
    op.drop_table("tenant_configs")
    op.drop_index(op.f("ix_prompts_tenant_id"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_name"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_offline_messages_visitor_id"), table_name="offline_messages")
    op.drop_index(op.f("ix_offline_messages_tenant_id"), table_name="offline_messages")
    op.drop_index(op.f("ix_offline_messages_session_id"), table_name="offline_messages")
    op.drop_table("offline_messages")
    op.drop_index(op.f("ix_mcp_servers_tenant_id"), table_name="mcp_servers")
    op.drop_table("mcp_servers")
    op.drop_index(op.f("ix_indexed_documents_tenant_id"), table_name="indexed_documents")
    op.drop_index(op.f("ix_indexed_documents_document_id"), table_name="indexed_documents")
    op.drop_table("indexed_documents")
    op.drop_index(op.f("ix_cost_records_tenant_id"), table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index(op.f("ix_alert_rules_tenant_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_alert_events_tenant_id"), table_name="alert_events")
    op.drop_table("alert_events")
    # ### end Alembic commands ###
